order: [pred32,pred64,pred128]
pred32:
  comp: multimodalattentivepooling.log.startendpred.TVRH5StartEnd
  args:
    start_name: st3
    end_name: end3
    duration: duration
    output: /content/drive/MyDrive/tvr2_pred32.json
pred64:
  comp: multimodalattentivepooling.log.startendpred.TVRH5StartEnd
  args:
    start_name: st21
    end_name: end21
    duration: duration
    output: /content/drive/MyDrive/tvr2_pred64.json
pred128:
  comp: multimodalattentivepooling.log.startendpred.TVRH5StartEnd
  args:
    start_name: st55
    end_name: end55
    duration: duration
    output: /content/drive/MyDrive/tvr2_pred128.json
