dataset: multimodalattentivepooling.dataset.tvr2.TVRH5
dataset_args: ./configs/baseline/ds_args.yaml
dataloader: torch.utils.data.DataLoader
dataloader_args: ./configs/baseline/dl_args.yaml
transforms: multimodalattentivepooling.transform.composite.CompositeTransform
transforms_args: ./configs/baseline/tf_args2.yaml
net: multimodalattentivepooling.model.tfbaseline2.Baseline
net_args: ./configs/baseline/net_args2.yaml
eval_args: ./configs/baseline/eval_args2.yaml
logger: multimodalattentivepooling.transform.composite.CompositeTransform
logger_args: ./configs/baseline/logger_args_eval2.yaml