order: [Segment,NormLRDist]
Segment:
  comp: multimodalattentivepooling.transform.segment.SegmentTarget2
  args:
    vis_name: vis_feats
    len_name: vis_len
    dur_name: duration
    ts_name: ts
    out_name: stgt
NormLRDist:
  comp: multimodalattentivepooling.transform.distance.NormalizedLRDist
  args:
    vis_name: vis_feats
    len_name: vis_len
    dur_name: duration
    ts_name: ts
    lout_name: ltgt
    rout_name: rtgt
