dataset: multimodalattentivepooling.dataset.tvr2.TVRH5
dataset_args: ./configs/baseline/ds_args_colab.yaml
dataloader: torch.utils.data.DataLoader
dataloader_args: ./configs/baseline/dl_args_colab.yaml
transforms: multimodalattentivepooling.transform.composite.CompositeTransform
transforms_args: ./configs/baseline/tf_args.yaml
optimizer: torch.optim.Adam
optimizer_args: ./configs/baseline/adam_args.yaml
net: multimodalattentivepooling.model.tfbaseline.Baseline
net_args: ./configs/baseline/net_args.yaml
loss: multimodalattentivepooling.transform.composite.CompositeTransform
loss_args: ./configs/baseline/loss_args_now.yaml
train_args: ./configs/baseline/train_args_colab.yaml