json_file: /Users/mohsenmalmir/Documents/data/captions/train_tvr.json
feats_h5file: /Users/mohsenmalmir/Documents/data/captions/sub_activitynet_v1-3.c3d.hdf5
query_h5file: /Users/mohsenmalmir/Documents/data/captions/anetq_train.hdf5
