dataset: multimodalattentivepooling.dataset.tvr2.TVRH5
dataset_args: ./configs/modchunks/ds_args_eval_colab.yaml
dataloader: torch.utils.data.DataLoader
dataloader_args: ./configs/modchunks/dl_args_colab.yaml
transforms: multimodalattentivepooling.transform.composite.CompositeTransform
transforms_args: ./configs/modchunks/tf_args.yaml
net: multimodalattentivepooling.model.modchunks4.ModulatedChunks
net_args: ./configs/modchunks/net_args.yaml
eval_args: ./configs/modchunks/eval_args.yaml
logger: multimodalattentivepooling.transform.composite.CompositeTransform
logger_args: ./configs/modchunks/logger_args_eval.yaml