order: [ChunkIoU,MaxPooledStartEnd]
ChunkIoU:
  comp: multimodalattentivepooling.transform.slidingwindow.ChunkIoU
  args:
    window_sizes: [3,6,9,12,21,33,42,54,66]
    num_chunks: [1,1,1,1,1,1,1,1,1]
    iou: 0.3
    in_name: vis_feats
    len_name: vis_len
    dur_name: duration
    ts_name: ts
    out_names: [win3gt,win6gt,win9gt,win12gt,win21gt,win33gt,win42gt,win54gt,win66gt]
MaxPooledStartEnd:
  comp: multimodalattentivepooling.transform.startend.MaxPooledStartEnd
  args:
    maxpool_size: 50
    len_name: vis_len
    dur_name: duration
    ts_name: ts
    start_outname: sttgt_maxpooled
    end_outname: endtgt_maxpooled
